### ISSUE TITLE
Using Multiple LayersLegend with LayerControl

### ISSUE THREAD

**Issue by Rafiosan** [iamtekson/leaflet-geoserver-request#10] opened 2021-08-03 17:48 UTC
Hello,

I am using your leaflet-geoserver-request code (thank you for providing it !!!!) on a huge bunch of layers that are controled/displayed via a Layer Control.

I would like to open the according Legend each time a Layer is Added to the map.

I tried to use a layerGroup to associate both the WMS layer and it's Legend in a single Layer triggered by the Control Layer, but unfortunately I have a message that states that the "The provided object is not a Layer".

DO you see a work-around to achieve what I tent to do ???

Thank you for your help.

Regards

Raphael

Here is the code I am using :

var norway_map = L.Geoserver.wms('http://15.236.29.28:8080/geoserver/cymo/wms', {
  layers: 'cymo:norway_floodmap' ,
  format: 'image/png',
  transparent: true,});
var norway_Legend = L.Geoserver.legend("http://15.236.29.28:8080/geoserver/cymo/wms", {
  layers: "cymo:norway_floodmap",
});
var norway_flood = L.layerGroup([norway_map, norway_Legend]);

the following message appears when I try to display norway_flood.

Layer.js:163 Uncaught Error: The provided object is not a Layer.
    at i.addLayer (Layer.js:163)
    at i.eachLayer (LayerGroup.js:123)
    at i.onAdd (LayerGroup.js:107)
    at i._layerAdd (Layer.js:114)
    at i.whenReady (Map.js:1465)
    at i.addLayer (Layer.js:176)
    at i._onInputClick (Control.Layers.js:383)
    at HTMLInputElement.c (DomEvent.js:92)

Thank you for your help one more time !!!!!

**Comment by iamtekson** [comment] 2021-08-06 08:38
Just by seeing the error message, I can't see what is wrong with your implementation. Can you reproduce your issue what do you want and what did you do?

**Comment by iamtekson** [comment] 2022-01-05 07:51
The issue was due to the legend URL `norway_Legend`. Since it will provide you with the PNG image as a response, you can not add it into the layer group. Please try to add only the relevant layers to the layer group. 

For now, I am closing this issue. If you think it is relevant, feel free to re-open it.

**Closed by iamtekson** 2022-01-05 07:51 UTC
Labels: question
